version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shelltalk
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shelltalk"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # server:
  #   build:
  #     context: ./shell-talk-server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     postgres: 
  #       condition: service_healthy
  #     mongo:
  #       condition: service_healthy
  #   environment:
  #     - POSTGRES_URL=postgres://user:password@postgres:5432/shelltalk?sslmode=disable
  #     - MONGO_URL=mongodb://user:password@mongo:27017

volumes:
  postgres-data:
  mongo-data:
